///\file print.c
///\brief File which contains the printing functions.
///\author Popa Ionut Iulian

#include <stdio.h>
#include "print.h"
#define INFINITY 99999

int *wae, it = 2;


///\fn void print_matrix(int **matrix, int nodes_number)

void print_matrix(int **matrix, int nodes_number){
    ///\brief This method will print a matrix.
    ///\param int **matrix graph's adjacency matrix.
    ///\param int nodes_number the number of graph nodes.
    int i, j;

    printf("%d nodes\n", nodes_number);

    for(i = 1; i <= nodes_number; i++){
        for(j = 1; j <= nodes_number; j++){
               printf("%5d ",matrix[i][j]%INFINITY);
        }
        printf("\n");
    }
}

void path(int **roy_floyd_matrix, int nodes_number, int start_node, int end_node){
    int k = 1, gasit=0;
    while( (k <= nodes_number) && (!gasit) ){
        if((k != start_node) && (k != end_node) && (roy_floyd_matrix[start_node][end_node] == roy_floyd_matrix[start_node][k] + roy_floyd_matrix[k][end_node]) ){
            path(roy_floyd_matrix, nodes_number, start_node, k);
            path(roy_floyd_matrix, nodes_number, k, end_node);
            gasit = 1;
        }
        k++;
    }
    if(!gasit){
        printf(" -> %d", end_node);
        wae[it] = end_node;
        it++;
    }
}
///\fn void show_path(int **roy_floyd_matrix, int nodes_number, int start_node, int end_node, int **matrix)


void show_path(int **roy_floyd_matrix, int nodes_number, int start_node, int end_node, int **matrix){
    ///\brief This method will print the path.
    ///\param int **roy_floyd_matrix the matrix generated by roy_floyd function
    ///\param int nodes_number the number of graph nodes.
    ///\param int start_node first node pf the path.
    ///\param int end_node last node pf the path.
    ///\param int **matrix graph's adjacency matrix.
    ///\brief print the path and distance between start and end

    if(roy_floyd_matrix[start_node][end_node] < INFINITY){
        printf("\nDistance between node %d and node %d = %d \n", start_node, end_node, roy_floyd_matrix[start_node][end_node]);
        printf("%d", start_node);
        wae = (int*)calloc(nodes_number + 1, sizeof(int));
        wae[1] = start_node;
        path(roy_floyd_matrix,nodes_number,start_node,end_node);
        printf("\n");
    }else{
        printf("There is no path between %d and %d \n", start_node, end_node);
    }

    ///print alternative route
    int i, j;
    printf("\nAlternative path for each consecutive nodes : \n");
    for(i = 1; i < it - 1; i++){
        int min_distance = INFINITY;
        int intermediary = -1;
        for(j = 1; j <= nodes_number; j++){
            if(matrix[wae[i]][j] + matrix[j][wae[i + 1]] < min_distance ){
                min_distance = matrix[wae[i]][j] + matrix[j][wae[i + 1]];
                intermediary = j;
            }
        }
        printf("Intermediary node between %d & %d : %d \n", wae[i], wae[i + 1], intermediary);
    }

}
