.TH "C:/Users/catal/Desktop/chestie 8/Roy_Floyd Directory Reference" 3 "Tue Jun 5 2018" "Roy_Floyd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/catal/Desktop/chestie 8/Roy_Floyd Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBgenerate\&.c\fP"
.br
.RI "File which contains the random generator\&. "
.ti -1c
.RI "file \fBgenerate\&.h\fP"
.br
.ti -1c
.RI "file \fBmain\&.c\fP"
.br
.RI "Main file where all the functions are called from\&. "
.ti -1c
.RI "file \fBprint\&.c\fP"
.br
.RI "File which contains the printing functions\&. "
.ti -1c
.RI "file \fBprint\&.h\fP"
.br
.ti -1c
.RI "file \fBroy_floyd\&.c\fP"
.br
.ti -1c
.RI "file \fBroy_floyd\&.h\fP"
.br
.in -1c
