.TH "C:/Users/catal/Desktop/chestie 8/Roy_Floyd/generate.c" 3 "Tue Jun 5 2018" "Roy_Floyd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/catal/Desktop/chestie 8/Roy_Floyd/generate.c \- File which contains the random generator\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <time\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'generate\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBINFINITY\fP   99999"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int ** \fBGenerateRandGraph\fP (int **matrix, int *nodes_number)"
.br
.in -1c
.SH "Detailed Description"
.PP 
File which contains the random generator\&. 


.PP
\fBAuthor:\fP
.RS 4
Popa Ionut Iulian 
.RE
.PP

.PP
Definition in file \fBgenerate\&.c\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define INFINITY   99999"

.PP
Definition at line 8 of file generate\&.c\&.
.SH "Function Documentation"
.PP 
.SS "int** GenerateRandGraph (int ** matrix, int * nodes_number)"
This method will generate an adjacency matrix and it will be stored in **matrix\&. 
.PP
\fBParameters:\fP
.RS 4
\fIint\fP **matrix graph's adjacency matrix\&. 
.br
\fIint\fP nodes_number the number of graph nodes\&.
.RE
.PP
Resize matrix
.PP
Generate random costs
.PP
Main diagonal 
.PP
Definition at line 13 of file generate\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Roy_Floyd from the source code\&.
