.TH "C:/Users/catal/Desktop/chestie 8/Roy_Floyd/generate.h" 3 "Tue Jun 5 2018" "Roy_Floyd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/catal/Desktop/chestie 8/Roy_Floyd/generate.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBINFINITY\fP   99999"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int ** \fBGenerateRandGraph\fP (int **matrix, int *nodes_number)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define INFINITY   99999"

.PP
Definition at line 1 of file generate\&.h\&.
.SH "Function Documentation"
.PP 
.SS "int** GenerateRandGraph (int ** matrix, int * nodes_number)"
This method will generate an adjacency matrix and it will be stored in **matrix\&. 
.PP
\fBParameters:\fP
.RS 4
\fIint\fP **matrix graph's adjacency matrix\&. 
.br
\fIint\fP nodes_number the number of graph nodes\&.
.RE
.PP
Resize matrix
.PP
Generate random costs
.PP
Main diagonal 
.PP
Definition at line 13 of file generate\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Roy_Floyd from the source code\&.
