.TH "C:/Users/catal/Desktop/chestie 8/Roy_Floyd/main.c" 3 "Tue Jun 5 2018" "Roy_Floyd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/catal/Desktop/chestie 8/Roy_Floyd/main.c \- Main file where all the functions are called from\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <conio\&.h>\fP
.br
\fC#include 'generate\&.h'\fP
.br
\fC#include 'print\&.h'\fP
.br
\fC#include 'roy_floyd\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBINFINITY\fP   99999"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Main file where all the functions are called from\&. 


.PP
\fBAuthor:\fP
.RS 4
Popa Ionut Iulian 
.RE
.PP

.PP
Definition in file \fBmain\&.c\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define INFINITY   99999"

.PP
Definition at line 7 of file main\&.c\&.
.SH "Function Documentation"
.PP 
.SS "int main ()"
Main function that takes user input to establish the start node and the end node of the path which want to be determined\&.
.PP
Copying matrix 'matrix' in "roy_floyd_matrix\&.
.PP
start_node The node in which the search starts\&.
.PP
end_node The node in which the search ends\&. 
.PP
Definition at line 14 of file main\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Roy_Floyd from the source code\&.
