.TH "C:/Users/catal/Desktop/chestie 8/Roy_Floyd/print.c" 3 "Tue Jun 5 2018" "Roy_Floyd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/catal/Desktop/chestie 8/Roy_Floyd/print.c \- File which contains the printing functions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'print\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBINFINITY\fP   99999"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprint_matrix\fP (int **matrix, int nodes_number)"
.br
.ti -1c
.RI "void \fBpath\fP (int **roy_floyd_matrix, int nodes_number, int start_node, int end_node)"
.br
.ti -1c
.RI "void \fBshow_path\fP (int **roy_floyd_matrix, int nodes_number, int start_node, int end_node, int **matrix)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int * \fBwae\fP"
.br
.ti -1c
.RI "int \fBit\fP = 2"
.br
.in -1c
.SH "Detailed Description"
.PP 
File which contains the printing functions\&. 


.PP
\fBAuthor:\fP
.RS 4
Popa Ionut Iulian 
.RE
.PP

.PP
Definition in file \fBprint\&.c\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define INFINITY   99999"

.PP
Definition at line 6 of file print\&.c\&.
.SH "Function Documentation"
.PP 
.SS "void path (int ** roy_floyd_matrix, int nodes_number, int start_node, int end_node)"

.PP
Definition at line 29 of file print\&.c\&.
.SS "void print_matrix (int ** matrix, int nodes_number)"
This method will print a matrix\&. 
.PP
\fBParameters:\fP
.RS 4
\fIint\fP **matrix graph's adjacency matrix\&. 
.br
\fIint\fP nodes_number the number of graph nodes\&. 
.RE
.PP

.PP
Definition at line 13 of file print\&.c\&.
.SS "void show_path (int ** roy_floyd_matrix, int nodes_number, int start_node, int end_node, int ** matrix)"
This method will print the path\&. 
.PP
\fBParameters:\fP
.RS 4
\fIint\fP **roy_floyd_matrix the matrix generated by roy_floyd function 
.br
\fIint\fP nodes_number the number of graph nodes\&. 
.br
\fIint\fP start_node first node pf the path\&. 
.br
\fIint\fP end_node last node pf the path\&. 
.br
\fIint\fP **matrix graph's adjacency matrix\&. print the path and distance between start and end
.RE
.PP
print alternative route 
.PP
Definition at line 48 of file print\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "int it = 2"

.PP
Definition at line 8 of file print\&.c\&.
.SS "int* wae"

.PP
Definition at line 8 of file print\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Roy_Floyd from the source code\&.
