.TH "C:/Users/catal/Desktop/chestie 8/Roy_Floyd/roy_floyd.c" 3 "Tue Jun 5 2018" "Roy_Floyd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/catal/Desktop/chestie 8/Roy_Floyd/roy_floyd.c
.SH SYNOPSIS
.br
.PP
\fC#include 'roy_floyd\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBINFINITY\fP   99999"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBroy_floyd\fP (int **roy_floyd_matrix, int nodes_number)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define INFINITY   99999"

.PP
Definition at line 7 of file roy_floyd\&.c\&.
.SH "Function Documentation"
.PP 
.SS "void roy_floyd (int ** roy_floyd_matrix, int nodes_number)"
This method will generate an matrix to find the shortest path and it will be stored in **roy_floyd_matrix\&. 
.PP
\fBParameters:\fP
.RS 4
\fIint\fP **roy_floyd_matrix the matrix generated 
.br
\fIint\fP nodes_number the number of graph nodes\&. 
.RE
.PP

.PP
Definition at line 12 of file roy_floyd\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Roy_Floyd from the source code\&.
